name: Ccompile

on:
  push:
  workflow_dispatch:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: haydenkow/nu-dcdev:release-4.7.3-rc3
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Compile doom
      run: |
        make
        ls
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: doom-${{ steps.slug.outputs.sha8 }}
        path: |
            DCDoom.bin
    - name: Create release for master branch
      if: github.ref == 'refs/heads/master'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest  build"
        files: DCDoom.bin
    - name: Create release form main branch
      if: github.ref == 'refs/heads/main'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest  Build"
        files: DCDoom.bin
